### ISSUE TITLE
Add "Project Page" section to Account Page

### ISSUE THREAD

**Issue by bibekkd** [code100x/cms-mobile#12]
#### Description:
I would like to add a new section called **Project Page** to the Account Page in the app. This section will allow users to manage and view their ongoing projects related to the courses they purchase.

#### Feature Details:
- **Section Name**: Project Page
- **Location**: Account Page (New section to be added above 'Terms & Conditions')
- **Functionality**: 
  - Display user projects
  - Include button to view details of each project 
  - Option to add new projects (if required)

#### Motivation:
The Project Page will enhance the user experience by providing users with easy access to their ongoing or completed course-related projects, making the app more interactive and valuable.

#### Additional Notes:
- The UI will follow the same styling as the rest of the app.

#### Tasks (TODO/Ongoing):
- [x] Create the "Project Page" section in the Account Page.
- [ ] Add UI components for listing and managing user projects.

#### References:
- Account Page structure.
- UI design principles for consistency with the existing app.

**Comment by ItsFlash10** [comment]
Good to have but not at this point, let's defer it for now
